[package]
name = "frontend"
version = "0.0.1"
edition = "2024"

# 24 deps total
[dependencies]
# logos is really the fattest at 19 deps and it pulls in chumsky
logos = "0.16.0"

# ariadne is 4 deps, ansi escapes is 1 (5 total, light shit)
ariadne = "0.4"
strip-ansi-escapes = "0.2"